In [20]:
import numpy as np
import sklearn
import pandas as pd

# 1. Matrices

## 1.1 Creatingn Matrices

In [21]:
# create a 2*2 array
arr = [[1,2],[3,4]]
print(arr)

[[1, 2], [3, 4]]


In [22]:
# Convert to numpy
np.array(arr)

array([[1, 2],
       [3, 4]])

In [23]:
import torch
print(torch.__version__)

1.0.1.post2


In [24]:
# Connvert to torch
torch.Tensor(arr)

tensor([[1., 2.],
        [3., 4.]])

## 1.2 Create Matrices with default values

In [25]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [26]:
torch.ones((2,2))

tensor([[1., 1.],
        [1., 1.]])

In [27]:
np.random.rand(2,2)

array([[0.15801528, 0.2574256 ],
       [0.59698827, 0.59651681]])

In [28]:
torch.rand(2,2)

tensor([[0.9440, 0.8458],
        [0.6051, 0.4691]])

## 1.3 Seeds for Reproduibility

In [31]:
# seed
np.random.seed(0)
np.random.rand(2,2)

array([[0.5488135 , 0.71518937],
       [0.60276338, 0.54488318]])

In [33]:
# seed
np.random.seed(0)
np.random.rand(2,2)

array([[0.5488135 , 0.71518937],
       [0.60276338, 0.54488318]])

In [36]:
# No seed
print(np.random.rand(2,2))
print('different output')

[[0.56804456 0.92559664]
 [0.07103606 0.0871293 ]]
different output


In [37]:
# Torch seed
torch.manual_seed(0)
torch.rand(2,2)

tensor([[0.4963, 0.7682],
        [0.0885, 0.1320]])

In [38]:
# torch seed
torch.manual_seed(0)
torch.rand(2,2)

tensor([[0.4963, 0.7682],
        [0.0885, 0.1320]])

In [39]:
# torch no seed
torch.rand(2,2)

tensor([[0.3074, 0.6341],
        [0.4901, 0.8964]])

#### Seed for GPU is different for now

In [42]:
print(torch.cuda.is_available())
if torch.cuda.is_available():
    torch.cuda.manual_seed_all(0)

True


## 1.3 Numpy and Torch Bridge
### Numpy to Torch

In [45]:
# numpy array
np_array = np.ones((2,2))
print(np_array)

[[1. 1.]
 [1. 1.]]


In [46]:
print(type(np_array))

<class 'numpy.ndarray'>


In [50]:
# Convert to torch tensor
torch_array = torch.from_numpy(np_array)
print(torch_array)
print(type(torch_array))

tensor([[1., 1.],
        [1., 1.]], dtype=torch.float64)
<class 'torch.Tensor'>


In [54]:
# Data types matter: intentional error
np_array_new = np.ones((2,2), dtype = np.int8)
torch.from_numpy(np_array_new)

TypeError: can't convert np.ndarray of type numpy.int8. The only supported types are: double, float, float16, int64, int32, and uint8.

#### The conversions support:
1. double
2. float
3. int64, int32, uint8

In [64]:
# Data type matters
np_array_new = np.ones((2,2), dtype = np.int64)
torch_array_new = torch.from_numpy(np_array_new)
print(torch_array_new)
print(torch_array_new.dtype)

tensor([[1, 1],
        [1, 1]])
torch.int64


### Torch to Numpy

In [70]:
torch_tensor = torch.ones(2,2)
type(torch_tensor)

torch.Tensor

In [72]:
torch_to_numpy = torch_tensor.numpy()
type(torch_to_numpy)

numpy.ndarray

## 1.4 Tensors on CPU and GPU

In [74]:
# cpu
tensor_cpu = torch.ones(2,2)
print(tensor_cpu)

tensor([[1., 1.],
        [1., 1.]])


In [75]:
# cpu to gpu
if torch.cuda.is_available():
    tensor_cpu.cuda()

In [76]:
# gpu to cpu
tensor_cpu.cpu()

tensor([[1., 1.],
        [1., 1.]])

## 1.5 Tensor operations

### Resizing tensors

In [78]:
a = torch.ones(2,2)
print(a)

tensor([[1., 1.],
        [1., 1.]])


In [81]:
print(a.size())


torch.Size([2, 2])


In [82]:
a.view(4)

tensor([1., 1., 1., 1.])

In [83]:
a.view(4).size()

torch.Size([4])

### element-wise addition

In [93]:
a = torch.ones(2,2)

In [94]:
b = torch.ones(2,2)

In [95]:
# element-wise addition
c = a+b
print(c)

tensor([[2., 2.],
        [2., 2.]])


In [96]:
# element-wise addition
c = torch.add(a,b)
print(c)

tensor([[2., 2.],
        [2., 2.]])


In [97]:
# In-place addition
print('Old C tensor')
print(c)

c.add_(a)
print('-'*60)
print('New C tensor')
print(c)

Old C tensor
tensor([[2., 2.],
        [2., 2.]])
------------------------------------------------------------
New C tensor
tensor([[3., 3.],
        [3., 3.]])


### element-wise subtraction

In [100]:
print(a)
print(b)


tensor([[1., 1.],
        [1., 1.]])
tensor([[1., 1.],
        [1., 1.]])


In [101]:
# Not in-place
print(a.sub(b))
print(a)

tensor([[0., 0.],
        [0., 0.]])
tensor([[1., 1.],
        [1., 1.]])


In [102]:
# In-place  sub_
print(a.sub_(b))
print(a)

tensor([[0., 0.],
        [0., 0.]])
tensor([[0., 0.],
        [0., 0.]])


### Tensor mean


In [112]:
a = torch.arange(1,11,1)
# convert to float tensor
a = a.type(torch.FloatTensor)
print(a)
print(a.size())

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])
torch.Size([10])


In [115]:
a.mean(dim=0)

tensor(5.5000)

In [127]:
a = torch.arange(1,11,1)
b = torch.arange(1,11,1)
a = torch.stack((a,b),0)
a = a.type(torch.FloatTensor)
print(a)

print(a.size())

tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
        [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]])
torch.Size([2, 10])


In [129]:
print(a.mean(dim=0))
print(a.mean(dim=1))

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])
tensor([5.5000, 5.5000])


### Tensor standard deviation

In [132]:
a = torch.Tensor([1,2,3,4,5,6,7,8,9,10])
print(a.std(dim=0))
print(torch.std(a,dim=0))

tensor(3.0277)
tensor(3.0277)


In [133]:
print(torch.cuda.is_available())

True


In [145]:
b = torch.ones(2,3)
print(b)

b.cuda()

tensor([[1., 1., 1.],
        [1., 1., 1.]])


tensor([[1., 1., 1.],
        [1., 1., 1.]], device='cuda:0')