# 2. Variables and Gradients

## 2.1 Variables
- A variable warps a tensor
- Allows accumulations of gradients

In [11]:
import torch
from torch.autograd import Variable

In [12]:
a = Variable(torch.ones(2,2), requires_grad = True)
a

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [13]:
# not a variable
torch.ones(2,2)

tensor([[1., 1.],
        [1., 1.]])

In [14]:
# Behaves similar to tensors
b = Variable(torch.ones(2,2), requires_grad = True)
print(a+b)
print(torch.add(a,b))

tensor([[2., 2.],
        [2., 2.]], grad_fn=<AddBackward0>)
tensor([[2., 2.],
        [2., 2.]], grad_fn=<AddBackward0>)


In [15]:
print(a*b)

tensor([[1., 1.],
        [1., 1.]], grad_fn=<MulBackward0>)


## 2.2 Gradients

In [42]:
x = Variable(torch.ones(2), requires_grad= True)
x

tensor([1., 1.], requires_grad=True)

In [43]:
y = 5*(x+1)**2
y

tensor([20., 20.], grad_fn=<MulBackward0>)

### Backward should be called only on a scalar

In [44]:
o = 0.5 * torch.sum(y)
o

tensor(20., grad_fn=<MulBackward0>)

In [45]:
o.backward(retain_graph = True)

In [46]:
x.grad

tensor([10., 10.])

In [47]:
# backward in detail
o.backward(torch.FloatTensor([1.0,1.0]))
x.grad

tensor([30., 30.])